name: Media Solutions Insider News
favicon: null
layout_spectrum: 0.76872
typography_spectrum: 0.23355826316401362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.17689107498154044
  saturation: 0.3125
  rhythmicContrast: 0.08391640591435134
purpose: []
